version: '3.8'

networks:
  pet-help:
    driver: bridge

services:
  pet-nginx:
    build:
      context: .docker
      dockerfile: nginx/Dockerfile
    container_name: pet-nginx
    ports:
      - "8080:80"
      - "9010:9001"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - pet-php
    networks:
      - pet-help
  pet-php:
    build:
      context: .docker
      dockerfile: php/Dockerfile
      args:
        user: nikul
        uid: 1000
    container_name: pet-php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - pet-postgres
    networks:
      - pet-help
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
  pet-postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: pet-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - pet-help
    volumes:
      - ./database:/var/lib/postgresql
